### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf1 in position 2076: invalid continuation byte

### ISSUE THREAD

**Issue by traines3812** [beta6/PassGAN#3]
Hello I am receiving this issue in both the none env and both env. I have tried changing different python versions as well any other advice on what I should try?

File "/home//passganenv/PassGAN/utils.py", line 102, in load_dataset
    lines=list(map(lambda x: x.strip("\n"), open(path, 'r').readlines()))
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf1 in position 2076: invalid continuation byte

**Comment by beta6** [comment]
Follow the instructions from previous posts. I wrote 2 articles with instructions in https://www.tuxrincon.com

**Comment by traines3812** [comment]
I did the following

i used python 3.9.2 . 
apt install python3-virtualenv
virtualenv passganenv
cd passganenv
source bin/activate
git clone https://github.com/beta6/PassGAN
pip install --upgrade pip
pip install -r PassGAN/requirements.txt
cd PassGAN

**Comment by beta6** [comment]
I understand that standard instructions didnt work.
if that dindnt work try cleaning a bit the dictionary with sed or some tool leaving charset similar to ascii standard. It fails because of utf-8 chars possibly.
The cleaning command should be something like 
sed -i '/[^\x00-\x7F]/d' your_file.txt
Make a copy of the diccionary before that.
The program worked for me with utf-8 diccionaries whatsoever but the previous instructions ensure that step.
Let me know if that worked or not to help a little or fix that.

**Comment by beta6** [comment]
Can you paste the full commandline that gives the error and the full trace please?

**Comment by traines3812** [comment]
python train.py --output-dir output --training-data data/train.txt

Traceback (most recent call last):
  File "/home/#####/PassGAN/train.py", line 116, in <module>
    lines, charmap, inv_charmap = utils.load_dataset(
                                  ^^^^^^^^^^^^^^^^^^^
  File "/home/#####/PassGAN/utils.py", line 102, in load_dataset
    lines=list(map(lambda x: x.strip("\n"), open(path, 'r').readlines()))
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe0 in position 0: invalid continuation byte

**Comment by beta6** [comment]
check the existence of both output directory and data/train.txt file. 
remember that its not needed to train rockyou dictionary nor crackstation nor darkc0de+openwall+xato-net-10M as they are already trained and included with git version and they can be used freely.
If you use another dictionary try cleaning it as i told you before with sed command from commandline

**Comment by traines3812** [comment]
ok I'll try with a custom and let you know here shortly

Thank you

**Comment by beta6** [comment]
import re, sys

def filter_ascii(binary_data):
    # Filter only ASCII characters from the binary data
    ascii_bytes = [b for b in binary_data if 0x00 <= b <= 0x7F]
    
    # Create a cleaned binary string using the filtered bytes
    cleaned_binary_data = bytes(ascii_bytes)
    
    return cleaned_binary_data.decode("ascii")



def clean_file(input_file, output_file):
    pattern = re.compile(r'[^a-zA-Z0-9!"#$%&\'()*+,\-./:;<=>?@[\]^_`{|}~\n\r\t]')
    with open(input_file, 'rb') as in_file, open(output_file, 'w') as out_file:
        for line in in_file:
            line=filter_ascii(line)
            if not pattern.search(line) and len(line)<12:
                out_file.write(line)

# Example usage
if len(sys.argv)>=3:
    clean_file(sys.argv[1], sys.argv[2])
else:
    print("%s <input file> <output file>")

**Comment by beta6** [comment]
`
import re, sys

def filter_ascii(binary_data):
    # Filter only ASCII characters from the binary data
    ascii_bytes = [b for b in binary_data if 0x00 <= b <= 0x7F]
    
    # Create a cleaned binary string using the filtered bytes
    cleaned_binary_data = bytes(ascii_bytes)
    
    return cleaned_binary_data.decode("ascii")



def clean_file(input_file, output_file):
    pattern = re.compile(r'[^a-zA-Z0-9!"#$%&\'()*+,\-./:;<=>?@[\]^_`{|}~\n\r\t]')
    with open(input_file, 'rb') as in_file, open(output_file, 'w') as out_file:
        for line in in_file:
            line=filter_ascii(line)
            if not pattern.search(line) and len(line)<12:
                out_file.write(line)

# Example usage
if len(sys.argv)>=3:
    clean_file(sys.argv[1], sys.argv[2])
else:
    print("%s <input file> <output file>")

`

**Comment by beta6** [comment]
i will upload to repo an utility (data/clean.py) that i used and get rid of this issue before training. 
Sorry for the inconvenience.

**Comment by beta6** [comment]
its uploaded. Using clean.py, the program train.py should run withouth errors.
Let me know if you find more issues.
Thanks for your feedback

**Comment by beta6** [comment]
tested and working with :
NVIDIA  Driver Version: 535.54.03      CUDA Driver Version: 12.2  Debian 11 / Ubuntu

**Comment by traines3812** [comment]
training is working thank you for your help and thanks for that clean.py sorry if I added any extra work.
