### ISSUE TITLE
Question on generating password

### ISSUE THREAD

**Issue by traines3812** [beta6/PassGAN#4]
Hello beta6 thank you again for help on original issue. THis one is more of a q/a.

I am currently training PassGAN with some custom wordlists using the example that has been around since the first iteration of passgan

python train.py --output-dir output --training-data data/train.txt

How would I go about making the custom wordlists? 

Would I follow one of these examples?

python sample.py \
	--input-dir csho10 \
	--checkpoint csho10/checkpoints/checkpoint_150000.ckpt \
	--output gen_passwords.txt \
	--batch-size 1024 \
	--num-samples 100000000

but change the input dir to output to match that of the custom wordlists and just choose a checkpoint?

**Comment by beta6** [comment]
well, when generating passwords you have 4 options:

A pretrained PassGAN model trained on the RockYou dataset : directory pretrained 10 chars
A pretrained PassGAN model trained on the darkc0de+openwall+xato-net-10M dataset 11 chars : directory commonu11
A pretrained PassGAN model trained on the crackstation-only-human dataset 10 chars : directory csho10

The 4th option is to train your own dictionary possibly with length 10-11 chars max each password with custom directory

When generating passwords with sample.py you need to choose one of this datasets and adjust all parameters according to the dataset of your choice.
Most of times pretrained datasets are good enough to generate very big dictionaries.

You can read more info in readme file and on the article : (https://www.tuxrincon.com/es/blog/passgan-como-generar-archivos-de-passwords-con-samplepy/)

**Comment by traines3812** [comment]
thank you
