### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by rafaelbs2** [beta6/PassGAN#8]
Hi, hope you are doing fine!

I faced this issue when trying to run sample.py:

PS C:\passgan> python .\sample.py --input-dir .\pretrained\ --checkpoint .\pretrained\checkpoints\195000.ckpt --output gen_passwords.txt --batch-size 1024 --num-samples 1000000

2024-11-13 14:31:59.529104: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library cudart64_110.dll
WARNING:tensorflow:From C:\Users\Main User\AppData\Local\Programs\Python\Python39\lib\site-packages\tensorflow\python\compat\v2_compat.py:96: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term
Traceback (most recent call last):
  File "C:\passgan\sample.py", line 91, in <module>
    charmap, inv_charmap = getmaps(args)
  File "C:\passgan\sample.py", line 79, in getmaps
    charmap = pickle.load(f)
UnicodeDecodeError: 'ascii' codec can't decode byte 0x83 in position 0: ordinal not in range(128)

Could you please help me to understand what is going on?

Using python 3.9.2 and CUDA 11.2 

Regards.

**Comment by beta6** [comment]
Sorry, I dont support Windows platform. This software its only tested on Linux

**Comment by rafaelbs2** [comment]
Ok, thanks for your answer. 

I have just installed the environment with linux. The sample.py worked fine!

But there was the following error with the train.py:

```
PassGAN$ python3.9 train.py --output-dir output --training-data data/train.txt
2024-11-19 11:03:24.292969: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudart.so.11.0
WARNING:tensorflow:From /home/crupto/.local/lib/python3.9/site-packages/tensorflow/python/compat/v2_compat.py:96: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term
[info] preprocessing...
[+] loading dictionary in memory...
Traceback (most recent call last):
  File "/home/crupto/crypto/passgan39/PassGAN/train.py", line 116, in <module>
    lines, charmap, inv_charmap = utils.load_dataset(
  File "/home/crupto/crypto/passgan39/PassGAN/utils.py", line 102, in load_dataset
    lines=list(map(lambda x: x.strip("\n"), open(path, 'r').readlines()))
  File "/usr/local/lib/python3.9/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf1 in position 2076: invalid continuation byte
```

Do you have any idea about whats may be wrong or how to fix it?

**Comment by beta6** [comment]
as i said previously in another post, you can use this utility to fix problems with utf-8 in dictionaries

https://github.com/beta6/PassGAN/blob/main/data/clean.py

**Comment by rafaelbs2** [comment]
Sorry that I missed your post! It was posted here on issues or your blog? I couldn't find.
Thanks a lot!
best regards!

**Comment by beta6** [comment]
It's on issues.
Thank you for using this software!
I hope you find it useful. Please let me know if you encounter any bugs or issues, and I will do my best to assist you.

Regards,

**Comment by rafaelbs2** [comment]
Thanks a lot! Training is working.

I have read your articles about training, and that it can take a long time. However, I suspect that something is not right. I started a training using the default options with a small word list (118) lines, however it has been running for almost 19 hours.

I have a 3080, which is operating at 20-40% of its capacity. I also have 16gb of RAM, and we are currently consuming less than 6gb.

Do you know what could be happening?

**Comment by beta6** [comment]
This software is designed to train with large dictionaries. Using small dictionaries may produce unexpected results. Think of a GAN as a pattern finder that generates results similar to those in the dictionary. If the dictionary is too small, the program may struggle to identify patterns and generate incorrect outputs.
